  - name: Set up Git
    run: |
      git config --global user.name 'github-actions'
      git config --global user.email 'github-actions@github.com'

  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: '16'  # Change this if necessary
      cache: 'npm'

  - name: Install dependencies
    run: npm ci

  - name: Run tests
    run: npm test -- --watchAll=false

  - name: Attempt to auto-merge
    if: success() && github.event.pull_request.mergeable == true  # Check if the PR is mergeable
    run: |
      git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge
      git checkout -qf FETCH_HEAD
      git checkout ${{ github.event.pull_request.base.ref }}
      git merge --no-ff ${{ github.event.pull_request.head.ref }} -m "Auto merge pull request #${{ github.event.pull_request.number }} from ${{ github.event.pull_request.head.ref }}"

  - name: Push changes
    if: success() && github.event.pull_request.mergeable == true  # Ensure the PR is mergeable before pushing
    run: |
      git push origin ${{ github.event.pull_request.base.ref }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure this token is set for authentication
      
### Key Changes:
- **Updated Checkout Action**: Changed `actions/checkout@v2` to `actions/checkout@v3` for the latest features and improvements.
  
- **Mergeability Check**: Added a check for `github.event.pull_request.mergeable` to ensure that the pull request is mergeable before attempting to merge and push changes.

- **Node.js Version**: Ensure that the Node.js version is appropriate for your project.

### Additional Considerations:
- **Error Handling**: If any of the steps fail, the workflow will stop executing further steps, which is the expected behavior for CI.

- **Testing**: Make sure that your tests are comprehensive enough to ensure that the code being merged is stable.
