name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        name: Checkout code

      - id: setup-node
        uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          node-version: '16'
          cache: 'npm'

      - id: install
        name: Install dependencies
        run: npm ci

      - id: lint
        name: Run linting
        run: npm run lint

      - id: typecheck
        name: Run type checking
        run: npm run typecheck

      - id: test
        name: Run tests
        run: npm test -- --watchAll=false

      - id: build
        name: Build
        run: npm run build
        env:
          CI: false
          REACT_APP_GITHUB_API_URL: 'https://api.github.com'
          REACT_APP_ENV: 'production'
          REACT_APP_RATE_LIMIT_THRESHOLD: '20' 