name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint || echo "Linting failed but continuing"
        
      - name: Run tests
        run: npm test || echo "Tests failed but continuing"
        
      - name: Build
        run: npm run build

      - name: Calculate CI/CD Value
        run: |
          mkdir -p config
          cp config/sample_ci_cd_metrics.yaml config/ci_cd_metrics.yaml
          python src/ci_cd_value.py
        continue-on-error: true

      - name: Upload Value Report
        uses: actions/upload-artifact@v2
        with:
          name: ci-cd-value
          path: |
            ci_cd_value_report.json
            ci_cd_value_plot.png
